name: Build for macOS, Windows and Linux
on:
  workflow_dispatch:
  push:
    branches: [dist-desktop]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: 'repo'
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Setup Defold
      uses: dapetcu21/setup-defold@v3
    - name: Setup LuaJIT
      uses: dapetcu21/gh-actions-lua@v8.0.0
      with:
        luaVersion: 'luajit'
    - name: Setup LuaRocks
      uses: leafo/gh-actions-luarocks@v4.0.0
    - name: Install LuaFileSystem
      run: 'luarocks install luafilesystem'
    - name: Import Code-signing certs
      uses: apple-actions/import-codesign-certs@v1
      with: 
        p12-file-base64: ${{ secrets.APPLE_CERTIFICATES_P12 }}
        p12-password: ${{ secrets.APPLE_CERTIFICATES_P12_PASSWORD }}
    - name: Set environment variables
      run: > 
        echo "MAC_IDENTITY=${{ secrets.MAC_IDENTITY }}" >> $GITHUB_ENV &&j
        echo "APPLE_ID=${{ secrets.APPLE_ID }}" >> $GITHUB_ENV &&
        echo "APPLE_ID_PASSWORD=${{ secrets.APPLE_ID_PASSWORD }}" >> $GITHUB_ENV &&
        echo "ASC_PROVIDER=${{ secrets.ASC_PROVIDER }}" >> $GITHUB_ENV
    - name: Make debug builds
      run: 'cd repo && lua deploy.lua_ package --debug --version-suffix .debug --skip-notarize'
    - name: Archive debug builds
      uses: actions/upload-artifact@v2
      with:
        name: debug
        path: repo/dist/package
    - name: Cleanup package dir
      run: rm -rf repo/dist/package
    - name: Make release builds
      run: 'cd repo && lua deploy.lua_ package'
    - name: Archive release builds
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: repo/dist/package