name: Build for macOS, Windows and Linux, then upload to S3
on:
  workflow_dispatch:
  push:
    branches: [dist-desktop]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  # MAC_IDENTITY: ${{ secrets.MAC_IDENTITY }}
  # APPLE_ID: ${{ secrets.APPLE_ID }}
  # APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
  # ASC_PROVIDER: ${{ secrets.ASC_PROVIDER }}

jobs:
  cache-lua:
    runs-on: ubuntu-latest
    steps:
    - name: Setup LuaJIT
      uses: dapetcu21/gh-actions-lua@v9.0.0
      with:
        luaVersion: 'luajit'

  build-debug:
    # runs-on: macos-latest
    runs-on: ubuntu-latest
    needs: 
      cache-lua
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: 'repo'

    - name: Setup Java
      uses: actions/setup-java@v1.4.3
      with:
        java-version: '11'

    - name: Setup Defold
      uses: dapetcu21/setup-defold@v3.0.2

    - name: Setup LuaJIT
      uses: dapetcu21/gh-actions-lua@v9.0.0
      with:
        luaVersion: 'luajit'

    # - name: Import Code-signing certs
    #   uses: apple-actions/import-codesign-certs@v1
    #   with: 
    #     p12-file-base64: ${{ secrets.APPLE_CERTIFICATES_P12 }}
    #     p12-password: ${{ secrets.APPLE_CERTIFICATES_P12_PASSWORD }}

    - name: Build
      run: 'lua deploy.lua_ package --debug --version-suffix .debug --skip-notarize'
      working-directory: 'repo'

    - name: Upload builds to S3
      run: 'aws s3 sync dist/package s3://${{ secrets.S3_BUCKET_BUILDS }}/$(./deploy.lua_ props title)/$(cat dist/package/VERSION.txt)'
      working-directory: 'repo'

  build-release:
    # runs-on: macos-latest
    runs-on: ubuntu-latest
    needs: cache-lua
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: 'repo'

    - name: Setup Java
      uses: actions/setup-java@v1.4.3
      with:
        java-version: '11'

    - name: Setup Defold
      uses: dapetcu21/setup-defold@v3.0.2

    - name: Setup LuaJIT
      uses: dapetcu21/gh-actions-lua@v9.0.0
      with:
        luaVersion: 'luajit'

    - name: Setup LuaRocks
      uses: leafo/gh-actions-luarocks@v4.0.0

    - name: Install LuaFileSystem
      run: 'luarocks install luafilesystem'

    # - name: Import Code-signing certs
    #   uses: apple-actions/import-codesign-certs@v1
    #   with: 
    #     p12-file-base64: ${{ secrets.APPLE_CERTIFICATES_P12 }}
    #     p12-password: ${{ secrets.APPLE_CERTIFICATES_P12_PASSWORD }}

    - name: Build
      run: 'lua deploy.lua_ package --skip-notarize'
      working-directory: 'repo'

    - name: Upload builds to S3
      run: 'aws s3 sync dist/package s3://${{ secrets.S3_BUCKET_BUILDS }}/$(./deploy.lua_ props title)/$(cat dist/package/VERSION.txt)'
      working-directory: 'repo'