name: Run tests
on:
  workflow_dispatch:
  push:
    branches: [dist]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v1.4.3
      with:
        java-version: '11'

    - name: Setup Defold
      uses: dapetcu21/setup-defold@v3.0.2

    - name: Resolve dependencies
      run: 'java -jar $BOB --auth "foobar" --email "john@doe.com" resolve'

    - name: Build project
      run: 'java -jar $BOB --variant debug build --keep-unused'

    - name: Run tests
      run: 'dmengine_headless --config=bootstrap.main_collection=/test/test.collectionc'

    - name: Upload coverage to CodeCov
      uses: codecov/codecov-action@v1.0.15
      with:
        token: ${{ secrets.CODECOV_TOKEN }}